# Generated by Django 4.2.13 on 2024-09-12 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_alter_cliente_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_cliente', to='cliente.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
