# Generated by Django 4.2.13 on 2024-09-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_name'),
        ('pedido', '0002_alter_pedido_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_cliente', to='cliente.cliente', verbose_name='Cliente'),
        ),
    ]
