# Generated by Django 4.2.13 on 2024-09-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0002_alter_pedido_client'),
        ('produto', '0002_alter_produto_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_produtos', to='pedido.pedido', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto_pedidos', to='produto.produto', verbose_name='Produto')),
            ],
        ),
    ]
