# Generated by Django 4.2.13 on 2024-09-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_produto', '0002_alter_pedidoproduto_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='product',
        ),
    ]
