# Generated by Django 4.2.13 on 2024-09-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_price'),
        ('pedido_produto', '0003_remove_pedidoproduto_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproduto',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Produto'),
        ),
    ]
