# Generated by Django 4.2.13 on 2024-09-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_client'),
        ('produto', '0002_alter_produto_price'),
        ('pedido_produto', '0004_pedidoproduto_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproduto',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='pedido.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_produto', to='produto.produto', verbose_name='Produto'),
        ),
    ]
