# Generated by Django 4.2.13 on 2024-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Preco')),
                ('stock', models.IntegerField(verbose_name='Estoque')),
            ],
        ),
    ]
